name: button_time
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8
  path: ^1.8.3
  path_provider: 2.0.0
  sqflite_common_ffi: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  tray_manager: ^0.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons8-停止-24.png
    - assets/icons8-停止-50.png
    - assets/icons8-开始-50.png
    - assets/icons8-时钟-50.png
